### PR TITLE
Allow character duplication

### PR DESCRIPTION
**Pull request by hguy**
**Add a new button for character duplication.**
image

**Ask for a new name.**
image

**Restart TQVault.**

**Note**
*Include various validation and safety.*
*Preserve progression & Stash.*

### CODE REVIEW

**Comment by hguy** [comment]
@EtienneLamoureux any problem with this feature ?

**Comment by EtienneLamoureux** [comment]
@hguy conflicts with your other PR :)

**Comment by hguy** [comment]
> @hguy conflicts with your other PR :)

Merged!

**Comment by hguy** [comment]
@EtienneLamoureux I just add a "save button" make sens with the new hot reload feature.

**Comment by hguy** [comment]
> Could we move the character dupe button in the character stats panel and make it obey the "Allow character modification" cheat?

Technicaly it doesn't modify any existing character.

**Comment by hguy** [comment]
I'm working on it and keep you in touch.

**Review by EtienneLamoureux — APPROVED** [review]

**Pull request merged**
