### PR TITLE
Add support for affixes loot table

### PR DESCRIPTION
**Pull request by hguy**
Purist can now choose item affixes from regular game loot table instead of farming duplicate and using the forge.

The name of the affix is added to the context menu.

**Theory crafting made easy!!**

## Updated documentation
https://github.com/hguy/TQVaultAE/blob/affixes-tables/documentation/AFFIXES.md
https://github.com/hguy/TQVaultAE/blob/affixes-tables/README.md

## Prefix
image

## Suffix
image

## Artefact completion bonus
image

## Relic and charm completion bonus
image

## Socketed relic and charm completion bonus
image

## Remove affixes
image

## Broken affixes when available
image

## Support of second relic completion bonus change
image

## You can switch affixes display by name/effect
image

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
This is very impressive!

**Review by EtienneLamoureux — APPROVED** [review]

**Comment by EtienneLamoureux** [comment]
Does it respects the game's limitations (Hallowed only on helmets) or is it free for all?

**Comment by hguy** [comment]
> Does it respects the game's limitations (Hallowed only on helmets) or is it free for all?

this join the loottable with the related itemid  (ItemId -> tableId -> AffixId) over all available DLC, so it should !

**Comment by hguy** [comment]
@EtienneLamoureux It actualy doesn't look at loot table that are "for alll". only those that are explicitely linked to items.

**Pull request merged**
