### PR TITLE
Added money editing options

### PR DESCRIPTION
**Pull request by mimic2300**
I think it would be good to be able to edit money as well :-)
A localization for all languages for the CEMoney key has also been added.

image

Damn... I accidentally committed localized comments in **Resources.Designer.cs** (I don't know how I did it) so you can ignore this file and add it manually
```csharp
        public static string CEMoney {
            get {
                return ResourceManager.GetString("CEMoney", resourceCulture);
            }
        }
```

### CODE REVIEW

**Comment by mimic2300** [comment]
Damn... I accidentally committed localized comments in **Resources.Designer.cs** (I don't know how I did it) so you can ignore this file and add it manually
```xml
<data name="CEMoney" xml:space="preserve">
    <value>Money</value>
</data>
```

**Comment by hguy** [comment]
Visual Studio 20XX regen automaticaly `Resources.Designer.cs` each time you update `Resources.resx`.
All `*.Designer.cs` should not be edited manually (except at merge time maybe).

**Comment by mimic2300** [comment]
> Visual Studio 20XX regen automaticaly `Resources.Designer.cs` each time you update `Resources.resx`. All `*.Designer.cs` should not be edited manually (except at merge time maybe).

So should I fix it or can you handle it? I would have to create a new PR for that.

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by hguy** [comment]
> > Visual Studio 20XX regen automaticaly `Resources.Designer.cs` each time you update `Resources.resx`. All `*.Designer.cs` should not be edited manually (except at merge time maybe).
> 
> So should I fix it or can you handle it? I would have to create a new PR for that.

I don't understand why you can't update your own PR ? Push a commit that fix your branch `mimic2300:feature/gold_edit` ?

**Comment by mimic2300** [comment]
Conflict fixed

**Comment by mimic2300** [comment]
Moved to: https://github.com/EtienneLamoureux/TQVaultAE/pull/444

**Pull request closed without merging**
