### PR TITLE
VXPlib Tooltip Full replacement using pure .NET Winform

### PR DESCRIPTION
**Pull request by hguy**
- VXPLib no more (C lib is fully removed)
- Hardcoded HTML mayhem no more (still a tiny piece for ItemProperties form needs a cleanup but the heavy lifting is done)
- Gives a rational model for gathering item display data (ToFriendlyNameResult)
- Open possibilities and necessary basecode for stuff like dockable/scrollable tooltips and graphical diff amongs item properties
- New StringHelper & TQColorHelper to handle TQ native colorization markup programmaticaly without HTML
- Display full qualified item name in BagButtonTooltip
- Cleanup FAQ & Vault "About" text

### CODE REVIEW

**Comment by s0da72** [comment]
>>>VXPLib no more (C lib is fully removed)

woot!  Break out champagne bottle and calibrate...  :)

**Comment by hguy** [comment]
Unfortunately it looks like the Ctrl + LClick multi selection doesn't work anymore !
I have to look at it.

**Comment by hguy** [comment]
Unless you see problems i think the base work is done on this topic.
@EtienneLamoureux the side quest fc32316 & 4fb3f44 can easily be cherrypicked on separate PR if needed.

**Comment by hguy** [comment]
An remember to cleanup the TagretDir when you build the release to prevent having the old file (VXPLib) in the Zip :)

**Comment by EtienneLamoureux** [comment]
> 
> 
> Unless you see problems i think the base work is done on this topic.
> @EtienneLamoureux the side quest [fc32316](https://github.com/EtienneLamoureux/TQVaultAE/commit/fc32316980c05cb5b3768132bebd664ab1047c5a) & [4fb3f44](https://github.com/EtienneLamoureux/TQVaultAE/commit/4fb3f44635c0546e9a50f9b808c111e0869a0167) can easily be cherrypicked on separate PR if needed.

Yeah I'd like that. I'll release the fixes on their own and then put in the major refactor.

**Comment by hguy** [comment]
> Yeah I'd like that. I'll release the fixes on their own and then put in the major refactor. For workshop maps: have they been integrated as part of the "custom map" functionality or made visible in the regular mode?

I just extend the "custom map" mechanism to steam workshop.
I agree, another upgrade on this could be to remove that combo box and make "modded characters" & "mod pack" available in regular mode.
But i'm not sure about itemid collision across multiple mod pack and may have impact on probably many level (minimum being "item info inaccuracy").
I don't know enough about mod structure to see if it's "safe" or not.

**Comment by hguy** [comment]
### **New Tooltip using Winform (No graphical changes with old one but faster on redraw)**
image

### **Detailed View Prefix/Base/Suffix (LeftAlt toggle)**
image

### **New bag tooltip**
image

### **Multi Column bag tooltip with optimized placement (if it's to big for regular placement)**
image

### **Dynamic left<->right placement by hovering on button surface**
image

**Comment by hguy** [comment]
### Old Pretty Filename
image

### New Pretty Filename
image

Now we can imagine an advanced filtering system to find specific relic by bonus parts in ComboBox (advanced search)
- Offense, Defense, Character
- Bleed, Cold, Attribute, etc...

**Comment by EtienneLamoureux** [comment]
> 
> 
> > Yeah I'd like that. I'll release the fixes on their own and then put in the major refactor. For workshop maps: have they been integrated as part of the "custom map" functionality or made visible in the regular mode?
> 
> I just extend the "custom map" mechanism to steam workshop.
> I agree, another upgrade on this could be to remove that combo box and make "modded characters" & "mod pack" available in regular mode.
> But i'm not sure about itemid collision across multiple mod pack and may have impact on probably many level (minimum being "item info inaccuracy").
> I don't know enough about mod structure to see if it's "safe" or not.

This is how I preferred it, hence why I asked. We'll never be able to fully support custom maps and characters.

**Comment by hguy** [comment]
> 
> 
> > > Yeah I'd like that. I'll release the fixes on their own and then put in the major refactor. For workshop maps: have they been integrated as part of the "custom map" functionality or made visible in the regular mode?
> > 
> > 
> > I just extend the "custom map" mechanism to steam workshop.
> > I agree, another upgrade on this could be to remove that combo box and make "modded characters" & "mod pack" available in regular mode.
> > But i'm not sure about itemid collision across multiple mod pack and may have impact on probably many level (minimum being "item info inaccuracy").
> > I don't know enough about mod structure to see if it's "safe" or not.
> 
> This is how I preferred it, hence why I asked. We'll never be able to fully support custom maps and characters.

Small thing that can be done is to filter character combobox to the current selected mod. for now all characters from all mods are visible.

**Comment by hguy** [comment]
I have just done a rebase to handle conflicts

**Comment by EtienneLamoureux** [comment]
Thanks. I think the current behaviour is acceptable.

**Comment by hguy** [comment]
### Better detection for Quest Items & Parchments

**Previously the text was in the Item name.**
image

**Previously it was blue**
image

**Comment by hguy** [comment]
@EtienneLamoureux that PR will probably fix #121 if it's VXPLib related

**Comment by EtienneLamoureux** [comment]
Is ctrl+Lclick functional too?

**Comment by hguy** [comment]
> 
> 
> Is ctrl+Lclick functional too?

Yes. It's fixed with 681e31a

**Comment by hguy** [comment]
@EtienneLamoureux Just to make people aware of the feature, maybe add in the QOL section 
`- Tooltip detailed view Prefix/Base/Suffix (Left-Alt toggle, no need to keep keydown)`

**Comment by hguy** [comment]
> 
> 
> > > Yeah I'd like that. I'll release the fixes on their own and then put in the major refactor. For workshop maps: have they been integrated as part of the "custom map" functionality or made visible in the regular mode?
> > 
> > 
> > I just extend the "custom map" mechanism to steam workshop.
> > I agree, another upgrade on this could be to remove that combo box and make "modded characters" & "mod pack" available in regular mode.
> > But i'm not sure about itemid collision across multiple mod pack and may have impact on probably many level (minimum being "item info inaccuracy").
> > I don't know enough about mod structure to see if it's "safe" or not.
> 
> This is how I preferred it, hence why I asked. We'll never be able to fully support custom maps and characters.

@EtienneLamoureux It can be achieved by keeping the reference to the mod (GamePathEntry) and arz/arc file at Item level and Player level. doing so we can avoid itemid collision/ambiguity by prioritizing mod file data read before fall back to regular game files.

**Pull request merged**
