### PR TITLE
Create a zip file during release build

### PR DESCRIPTION
**Pull request by epinter**

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
Is this to help with release?

**Comment by epinter** [comment]
Yes, not sure if worth it, is up to you...

**Comment by EtienneLamoureux** [comment]
It's most likely a good idea to automate as much as possible. I'm also zipping a self-extracting archive in an `.exe` for the releases.

**Comment by NorthFury** [comment]
Didn't work for me. the compress command was not recognized.

**Comment by epinter** [comment]
I'm using Windows 10... What kind of error you have if you run the powershell compress-archive from CMD ?

**Comment by NorthFury** [comment]
From error log:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "xcopy "E:\work\tqvault\TQVaultAE\libs" "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\" /y
xcopy "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release" "E:\work\tqvault\TQVaultAE\bin\Release" /y /s /i
cd "E:\work\tqvault\TQVaultAE\bin\Release"


if /I NOT "Release" == "Debug" (
del "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\*.pdb" 2> NUL
del "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\tqdebug.txt" 2> NUL
del "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\*.vshost.exe" 2> NUL
del "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\*.vshost.exe.manifest" 2> NUL
del "E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\*.vshost.exe.config" 2> NUL
powershell.exe Compress-Archive -Path E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\Release\*" -DestinationPath "E:\work\tqvault\TQVaultAE\bin\TQVaultAE.zip" -force
)
" exited with code 1.	TQVaultAE.GUI			
```
From Output:
```
3>  The term 'Compress-Archive' is not recognized as the name of a cmdlet, function
3>  , script file, or operable program. Check the spelling of the name, or if a pat
3>  h was included, verify that the path is correct and try again.
3>  At line:1 char:17
3>  + Compress-Archive <<<<  -Path E:\work\tqvault\TQVaultAE\src\TQVaultAE.GUI\bin\
3>  Release\* -DestinationPath E:\work\tqvault\TQVaultAE\bin\TQVaultAE.zip -force
3>      + CategoryInfo          : ObjectNotFound: (Compress-Archive:String) [], Co 
3>     mmandNotFoundException
3>      + FullyQualifiedErrorId : CommandNotFoundException```

**Comment by NorthFury** [comment]
I'm on Windows 7 still.

**Pull request closed without merging**
