### PR TITLE
Export as CSV to Clipboard

### PR DESCRIPTION
**Pull request by hguy**
Implement CSV export as suggested in #437.

Translation : EN/FR.

## Context menu
image

## Settings
image

## Added documentation for Arz Explorer & Save File Explorer
https://github.com/hguy/TQVaultAE/blob/export-to-csv/documentation/ARZEXPLORER.md
https://github.com/hguy/TQVaultAE/blob/export-to-csv/documentation/SAVEFILEEXPLORER.md

## Added documentation for advanced search
https://github.com/hguy/TQVaultAE/blob/export-to-csv/documentation/ADVANCEDSEARCH.md

## Added advanced search category filtering
image

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
This one conflicts quite a bit :/

**Comment by hguy** [comment]
I'm not available right now but i'll look at it in days coming

**Comment by hguy** [comment]
@EtienneLamoureux it should be OK

**Comment by hguy** [comment]
@EtienneLamoureux Merge done

**Comment by hguy** [comment]
Revert to far in history. I did a clean rebase and a new PR.

**Pull request closed without merging**
