### PR TITLE
Add support for Chinese

### PR DESCRIPTION
**Pull request by AirsQ**
Hi

I tried to add support for Chinese.
And my local test is OK.

Have a look.

Thank you.

### CODE REVIEW

**Comment by hguy** [comment]
You can find a fixe for testing.
It include some simplification.
[fix-chinese-implementation.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/8281670/fix-chinese-implementation.zip)
g

**Comment by hguy** [comment]
@AirsQ btw this is a great job ;) Handling all this translations is a big task.

**Comment by AirsQ** [comment]
OK， I will try。

**Comment by hguy** [comment]
> 

look in the zip, it's a fix from your branch.

**Comment by hguy** [comment]
@AirsQ i pushed a PR with the fix on your branch.

**Pull request closed without merging**
