### PR TITLE
Split GUI : Presentation layer upgrade

### PR DESCRIPTION
**Pull request by hguy**

### CODE REVIEW

**Comment by epinter** [comment]
`2019-06-18 21:30:13,265 [1] ERROR TQVaultAE.GUI.Program [(null)] - The type initializer for 'TQVaultAE.Presentation.FontHelper' threw an exception.
System.TypeInitializationException: The type initializer for 'TQVaultAE.Presentation.FontHelper' threw an exception. ---> System.ArgumentException: Font 'Albertus MT' cannot be found.
   at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
   at System.Drawing.FontFamily..ctor(String name)
   at TQVaultAE.Presentation.FontHelper..cctor()
   --- End of inner exception stack trace ---
   at TQVaultAE.Presentation.FontHelper.set_FontLoader(IAddFontToOS value)
   at TQVaultAE.GUI.Program.Main()
2019-06-18 21:30:13,292 [1] ERROR TQVaultAE.GUI.Program [(null)] - An application error occurred.
System.TypeInitializationException: The type initializer for 'TQVaultAE.Presentation.FontHelper' threw an exception. ---> System.ArgumentException: Font 'Albertus MT' cannot be found.
   at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
   at System.Drawing.FontFamily..ctor(String name)
   at TQVaultAE.Presentation.FontHelper..cctor()
   --- End of inner exception stack trace ---
   at TQVaultAE.Presentation.FontHelper.set_FontLoader(IAddFontToOS value)
   at TQVaultAE.GUI.Program.Main()`

**Comment by hguy** [comment]
this is because the Contributing Section "Tool chain setup" should say

In order to have a proper rendering of the controls in visual studio winform designer, _as a developer you **must**_ install  in your system the following truetype fonts.
- ${solutionDir}\src\TQVaultAE.Presentation\Resources\Fonts\albertus mt light.ttf
- ${solutionDir}\src\TQVaultAE.Presentation\Resources\Fonts\albertus mt.ttf

But there is none.
An other quick and dirty fix, could be to use "Safe font" by default, but new comers could not be aware and design new form or old one with font mixing without knowing it.

So what do we choose ?

**Comment by hguy** [comment]
No you're right it's happening at run time also. i look at it.

**Comment by hguy** [comment]
Should be ok

**Comment by epinter** [comment]
@EtienneLamoureux can you rebase and merge ?

**Comment by EtienneLamoureux** [comment]
I can do it. For these types of sweeping changes I agree, but normally it's easier to squash and have one feature per pull request.

**Pull request merged**
