### PR TITLE
Add optional colored backgrounds to items

### LINKED ISSUE #138: Add optional colored backgrounds to items
Allow, through an option, to display the items rarity as a colored background. This was added in the Atlantis Expansion and it would be nice to mirror it in TQVaultAE.

### PR DESCRIPTION
**Pull request by hguy**
Fix #138

### CODE REVIEW

**Comment by hguy** [comment]
Add colorized background for **Common, Rare, Epic, Legendary** items.
image

Add configuration setting for background color opacity.
image

**Comment by hguy** [comment]
**Display when activated. Default is False.**
image

**Comment by EtienneLamoureux** [comment]
Wow, this is huge, thanks a ton. It's nice we can follow closely what the game has.

**Comment by hguy** [comment]
> 
> 
> Wow, this is huge, thanks a ton. It's nice we can follow closely what the game has.
@EtienneLamoureux Thanks ! Unfortunately a little bit of math is missing for the red BG color.
Do you know a smart modder to add that last piece to this feature ?
Ultimately even if we had the good math, we don't have the good values on the item affixes. We should resolve this first.

**Comment by EtienneLamoureux** [comment]
Included in https://github.com/EtienneLamoureux/TQVaultAE/pull/266

**Pull request closed without merging**
