### PR TITLE
Disable Relic, Charm & Potion stacking and Stuff!

### LINKED ISSUE #278: Add new option to disable Relic, Charm & Potion stacking
Please consider adding an option to disable Relic and Charm stacking and completion, and Potion stacking, for a "purist" way of using TQVaultAE only for muling. Currently it's easy to accidentally stack Relics, Charms and Potions when the intention is to just move them around.

Especially the Relic - and probably Charm too, didn't test that - completion bothers me slightly, because the Completion Bonus works in a bit different way in-game. More info below.

P.S. Also, I did a quick test on how Relic Seed affects the Completion Bonus. I had 3 pieces (piece = 1/3rd of a Relic) of a Relic each with a different Seed, let's call this a set. Then I Duplicated the set multiple times, so that I could repeat the combining of the Relic pieces, doing it always in the same order, e.g. Set 1 = Seed 1 -> 2 -> 3; Set 2 = Seed 1 -> 2 -> 3; etc.

Combining the Relics this way in TQVaultAE seems to randomize the completion bonus according to the Completion Bonus weightings, which seems logical and how it should work. But, in-game, the Completion Bonus was always the same for each set, because the Seeds of the pieces were identical in each set.

Of course in practice that doesn't really make much of a difference, because the Relics' Seeds are going to be random anyway, but the bottom line is that there is a difference in how the Completion bonuses are handled in TQVaultAE compared to the game.

Anyway, these are minor things and the tool itself is great. Thanks to all involved in creating it!

### LINKED ISSUE #287: System.IO.FileLoadException: Could not load text DB
When i open the TQVaultAE.exe i have this error.
System IO FileLoadException

### LINKED ISSUE #442: Display the effects of the new Eternal Embers potions in the tool
### In Game
image

### In TQVault
image
[Share.vault.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/8883820/Share.vault.zip)

### LINKED ISSUE #467: "Error System invalid"
Hello ! 

I'm here because I can't get Tqvault to work. I just dll the new version (4.3) with the modifications for the "Autodetectgamepath" but I still have a message that blocks me despite the modifications.
I never managed to configure it with Titan Quest AE while with IT it works correctly.

Thanks in advance and have a nice day!

image

### LINKED ISSUE #469: Add a character save management system
Over time, the number of character saves is growing.
It can be a real chore to scroll through all your character in the main screen of the game.

It would be nice to be able to create "character tags" and be able to deploy on demand in the regular save directory characters assigned to each tags.

You only want to play regularly with a small set of characters and sometime replaying an old one.

Technicaly it's about moving characters directories in and out `$(TQSaveDirectory)\SaveData\Main` (\User for mods) in a comprehensive way.

Archived character directories would be stored in the `\ArchivedCharacters` subdirectory.

Tag mappings would be stored as a json in `\ArchivedCharacters\tqvault-tags.json` file.
```json
{
	"tags" : [
		{
			"name" : "HCDungeonPushing", 
			"color" : {
				"R" : 10, 
				"G" : 11, 
				"B" : 12 
			}
		},
		{
			"name" : "AllDefense", 
			"color" : {
				"R" : 20, 
				"G" : 21, 
				"B" : 22 
			}
		}
	],
	"mapping" : [
		{ "player" : "Main\\_character1", "tags" : ["AllDefense"] },
		{ "player" : "Main\\_character2", "tags" : ["AllDefense", "HCDungeonPushing"] },
		{ "player" : "User\\_characterMod", "tags" : ["HCDungeonPushing"] },
	]
}
```

The shelved characters should still be available for selection, management and search through. TQVault code must adapt to that new directory structure.

A modal window should be available for tag management (basic CRUD operations) and tag assignments.

Tags should be visible, if possible, in the dropdown item near the name of the character (rendered in color).

The BackGroundColor of the dropdownitem, should indicate if the character is "archived" or not (some grey color VS normal white).

A context menu on the DropDown control should be available for fast "tag assignment" of the selected character,  "Shelve/Unshelve current character" and "Shelve/Unshelve per tag".

### LINKED ISSUE #471: Make 'Set Items' a 'highlights items having' option.
Hey there, i wonder if it would be possible to query for set items in general. Basicly a button in search that highlights all items that also get shown in https://tq-db.net/en/set.

### PR DESCRIPTION
**Pull request by hguy**
## Fix #278 disable Relic, Charm & Potion stacking
You can configure it from the user settings.
Default is uncheck.
image

## Add "Having Relic", "Having Charm" into Highlight
image

## Resolve #442 Display the effects of EE potions
image

## Revamp configuration window
image

## Cloud backup via Git
image

Documentation here
https://github.com/hguy/TQVaultAE/blob/disable-stacking/documentation/GITBACKUP.md

## Add support for TQ original character saves

Documentation here
https://github.com/hguy/TQVaultAE/blob/disable-stacking/documentation/TQORIGINAL.md

## Close #471 - Add Highlight "Set Item" filter
image

## Refresh Advanced Search
This update is closing the gap between the "Highlight" form and the "Search" form.

- Added missing filters from "Highlight"
image
image

- Better Form response to Resize
- Query persistance include all filters & UI state
- New JSON file for Query saves (`SearchQueries.json`).
- Updated documentation
  - https://github.com/hguy/TQVaultAE/blob/disable-stacking/documentation/ADVANCEDSEARCH.md#requirement-filters
- New categories
image

## Close #469 - Add a character save management system
image
- New character ComboBox with a tool menu
  - "Duplicate" feature has been moved here
  - New "Archived/Unarchived" feature
    - Archived character have a silver background color when selected
    - Archive/Unarchive all
image

  - New "Tags" feature
    - Full tag management system here
    - You can "Mass Archive/Unarchive characters" by tag

- New Detailed DropDown to support theses features
image
  - Display the exact save file version (TQ, TQIT, TQAE)
  - Display tags
  - Detailed Masteries

Documentation here
https://github.com/hguy/TQVaultAE/blob/disable-stacking/documentation/CHARMANAGE.md

## Others
- Fix #287 Error when no save found
- Fix #467 by making path editing much clearer
- Updated overall nuget dependencies to latest.
- Fixed binary tool when searched key is not found.
- New `/TQVaultData/Config/` directory for config file persistance.
  - `SearchQueries.json`
  - `TagConfig.json`
- Use vault Icon instead of label.
image

### CODE REVIEW

**Comment by hguy** [comment]
@EtienneLamoureux it looks like the old TQ game has a built in mecanism that detect when an item has been added or removed from the `player.chr` and make the altered save unplayable (tested on steam). I tried to understand and trick the system but in vain for now.
Putting back the item at the exact same place make the save work again. 
So it's not about file format integrity.
It's not a comparison with last backup file either because tweaking the backup file doesn't break the save.
It looks more like a checksum check where the hash is... somewhere.

The solutions are one of these 
- Making TQ Original save `Read Only` for TQVault (there is a variant of this idea in issue #268 for vault).
- Excluding TQ Original save file from the return value of `IGamePathService.GetCharacterList()` until we have a solution (read only or other).

For now i'm excluding the feature (option 2), just to be non blocking on the PR.

Considering the facts, i don't think TQVaultAE ever worked with Titan Quest Original.

Maybe @ejfudd have some insight about this?

**Comment by ejfudd** [comment]
@hguy That does sound familiar.  I checked my file decoding notes and I did not see anything there about a checksum.  I do have the original TQVault 2.1 code somewhere and it should be in there. I will dig it up and take a look.

**Comment by hguy** [comment]
> @hguy That does sound familiar. I checked my file decoding notes and I did not see anything there about a checksum. I do have the original TQVault 2.1 code somewhere and it should be in there. I will dig it up and take a look.

I confirm that if checksum it is, it's not stored inside the Player.chr after 30 min doing binary compare on this file, i didn't detect any differences except the items. TQVault fully support the TQ Original file format.

> Edit: With the original Titan Quest, we used a utility called TQVaultMon which would monitor the Titan Quest process and disable the anti-cheat for modifying your character.

It looks like i just hit the wall of this anti-cheat. I can't find anything about this "TQVaultMon". Do you have any copy, any code somewhere, any link ?

**Comment by ejfudd** [comment]
@hguy I was able to find the source for TQVault 2.3.1.4. I have extracted the TQVaultMon project and attached it.

To be honest, TQVaultMon is a relic from before I took over TQVault. The code just does an in-memory patch of the Titan Quest exe file to bypass the anti-cheat. The actual patches were provided by Soulsekkor of TQDefiler fame.

[TQVaultMon.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/9463224/TQVaultMon.zip)

**Comment by hguy** [comment]
@ejfudd Thanks! my investigation lead me to soulseeker/TQDefiler work on this to.
I just decompile the tool to have a look.
Looks like his patch work for v1.2-v1.3, but steam current version is labeled "v1.3.sd" and defiler doesn't support it. I have to look at this a little bit closer when i have time.

**Comment by hguy** [comment]
@ejfudd @EtienneLamoureux well i did compromise.
https://github.com/hguy/TQVaultAE/blob/disable-stacking/documentation/TQORIGINAL.md

**Comment by ejfudd** [comment]
That was probably the quickest and simplest fix.  
If the process fix in TQDefiler.NET still works for TQ 1.3, TQVaultMon should also work.  I can post a binary from one of the older TQVault versions or you can create one from the project that I attached previously.  Of course, that's if you want to pursue it.

**Comment by hguy** [comment]
> That was probably the quickest and simplest fix. If the process fix in TQDefiler.NET still works for TQ 1.3, TQVaultMon should also work. I can post a binary from one of the older TQVault versions or you can create one from the project that I attached previously. Of course, that's if you want to pursue it.

That's what i though first, and it certainly must with CD versions until v1.30, but for some reason the Steam version have a memory allocation that TQVaultMon can't handle and TQDefiler does. My prefered solution was to apply patch directly on the TitanQuest.exe, but the Steam binary is also slightly different and i didn't succeed either.
I only use steam version and i don't have any iso for older version, so my testing capability is limited.

**Comment by hguy** [comment]
Hi @EtienneLamoureux,
Is there any blocking code in this PR ?

**Comment by EtienneLamoureux** [comment]
> Hi @EtienneLamoureux, Is there any blocking code in this PR ?

No, it should be all good :)

Are all the changes documented above?

**Review by EtienneLamoureux — APPROVED** [review]

**Comment by hguy** [comment]
> Are all the changes documented above?

When documentation was needed, yes!

**Pull request merged**
