### PR TITLE
Refacto : Add DependencyInjection

### PR DESCRIPTION
**Pull request by hguy**
-  Use standard Microsoft.Extensions.DependencyInjection
- Make TQVaultAE.Domain the center of the app to achieve DI integration
- Finish Model/Providers spliting on TQVaultAE.Data (Data layer goes full DI)
- Split responsibility between TQDataService & GamePathService
- #4 can be started rationally without willing to die trying 
- Implemented up to ArzExplorer to make everything work

### CODE REVIEW

**Comment by hguy** [comment]
#195 is in this PR.

**Comment by EtienneLamoureux** [comment]
Also, it seems there are some dependency error in ARZExplorer.

**Comment by hguy** [comment]
> 
> 
> Also, it seems there are some dependency error in ARZExplorer.

@EtienneLamoureux Did you fix it ? I can't see it in master ?

**Comment by hguy** [comment]
> 
> 
> Alright, that's ok.
> 
> Two things:
> 
>     * Just so I know when I'll be able to stop fixing conflicts, how many more sweeping architectural changes are you still planning?
Github didn't mention about conflict when i push the PR.
There is no plan for big changes like i did previously. DI was the last big change on the base code.
>     * In the future, could you separate your PRs and make one per refactor/issue fixed whenever possible?
Yes

**Comment by EtienneLamoureux** [comment]
Alright cool. And no worries, the conflicts are with some local branches I have.

**Pull request merged**
