### PR TITLE
Increase vault size to 18x20 and rework main form

### PR DESCRIPTION
**Pull request by epinter**
tqvault_screenshot2
tqvault-screenshot1

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
This is pretty amazing. I'll bump the minor version at least.

**Comment by epinter** [comment]
I tried to keep the screen height shorter as I could... This was the best was I found to increase the size. Every other way I tried, I ended up trading 50px of height for 8 lines of vault...

**Comment by NorthFury** [comment]
Nice work epinter. There is one problem that I can see. A lot of laptop displays have lower resolutions then the 910 that is the default with this size.

**Comment by epinter** [comment]
I made some tests, didn't found better way... It's possible to reduce a bit (like 50px or 80px, but didn't worth it). I think it's not so critical because we can trust the scaling.

**Comment by epinter** [comment]
Also, I don't think we should avoid the increase because users limited to 768px... The majority certainly isn't this kind of user. With scaling they still be able to use...

**Comment by NorthFury** [comment]
There is a way to reduce it by a lot more but I think it's a bit more involved. It would require putting the Inventory Area as a new tab next to Equipment/Transfer Area/Storage Area. The other solution that I've seen is having a toggle between inventory and the rest (not so pretty).

**Comment by epinter** [comment]
Maybe we could reduce the "default scaling", don't know if it's easy to implement...

**Comment by epinter** [comment]
I think we don't need to worry, TQVault already scale automatically: https://github.com/EtienneLamoureux/TQVaultAE/blob/1f0cf15aff783ec3f86e81f33f27063127c6aaca/src/TQVaultAE.GUI/MainForm.cs#L950

**Comment by NorthFury** [comment]
It doesn't take the taskbar into consideration but you are right. It does fit to max height.

I'm looking now to see how much of a pain it would be to put the inventory as a tab.

**Comment by epinter** [comment]
Wouldn't be confusing to switch inventory using a tab ? We can change the calc to reduce the scale.

like:

this.ScaleForm((Convert.ToSingle(Screen.PrimaryScreen.Bounds.Height) / Convert.ToSingle(this.Height)*0.95, false);

**Comment by NorthFury** [comment]
I don't think it would be confusing. Everything related to a player is in the tab view. the stash and the transfer stash are already there. The only thing that would change is adding the inventory and inventory bags to one new tab. Here is a rough sketch:
inventory

**Comment by epinter** [comment]
Personally, when I look this sketch, there's something that is not in the right place... I think the player inventory, storage area and transfer area are things we whould left the visual like they are in game... 

The scalling adjust on lower resolutions should work. What you think ?

**Comment by NorthFury** [comment]
I agree with relying on scaling. As an added bonus. if we keep the height of the vault to 20 squares, it will be compatible with the TQVault XL files that some people are using already. Here are some screen-shots from the XL version.

**Comment by NorthFury** [comment]
Looking at the screenshots I just posted I got inspired. We could get a bit of height by removing the char/vault name labels and using the combo boxes for the name of the selection. The labels seem redundant anyhow. The information is already displayed. What do you think?

**Comment by epinter** [comment]
To be honest, I think the scaling adjust is necessary even if we change the interface to any other way.

So I will add one commit with the change. I think we can merge this if everything works fine. And if we find a better way to place the panels, we can change in the future.

**Comment by epinter** [comment]
I tried to remove the labels. To be honest I prefer without the redundant labels, but I left to avoid radical changes.

**Comment by epinter** [comment]
Commit added, can you test for me ? I don't have visual studio here atm.

**Comment by NorthFury** [comment]
Interestingly enough, on the first run the UI seems to be scaled down but not the window. On the second run all look good.

**Comment by NorthFury** [comment]
This is a better fix:
```cs
this.ScaleForm(Convert.ToSingle(Screen.PrimaryScreen.WorkingArea.Height) / Convert.ToSingle(this.Height), false);
```

**Comment by epinter** [comment]
OK, done. :)

**Comment by epinter** [comment]
Ready to merge


screenshot

**Comment by NorthFury** [comment]
@EtienneLamoureux seeing how you already approved the redesign, I'll merge this later today in order to draft a new release.

**Pull request merged**
