### PR TITLE
Fix equipment background corruption removing background cursor feature

### PR DESCRIPTION
**Pull request by epinter**

### CODE REVIEW

**Comment by epinter** [comment]
Needs a lot of test. I tested just a few times...

**Comment by NorthFury** [comment]
I don't know what this refers to and what I should test for. Could you please expand on it.

**Comment by epinter** [comment]
When you scale the window, the background of equipment panel (where the player's equipped items stay) doesn't scale properly, artifacts from the window before the scale stay below the items.

**Comment by epinter** [comment]
Commit rebased.

**Comment by epinter** [comment]
Tested, didn't found bugs.

**Pull request merged**
