### PR TITLE
Relic Vault full support

### PR DESCRIPTION
**Pull request by Ninakoru**
Full support to the "Relic Vault" shared stash, with this functionalities:

- Added a fourth tab that loads the new relic stash data, with proper handlers if the Relic Vault stash doesn't exist and any expected errors.

- You can freely copy/duplicate/change seed or move items from this relic vault and other item placeholders as any other stash, but with item type restriction on entry, which leads to the next point.

- To emulate in-game functionality and to avoid possible issues, this stash only admits relics, charms, artifacts & artifact recipes. Any other type of item will be blocked either from cursor pick and deploy (shows red invalid when the picked item is over the Relic Vault cells) or canceled using the "Move item to > Stash" feature form the left button menu (any invalid item will be cancelled from the individual or bulk transfer).

I tested all the stuff extensively with in-game testing too, but any extra testing is welcome.

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
Impressive! Fixes #108

**Comment by EtienneLamoureux** [comment]
Fixes #118

**Comment by EtienneLamoureux** [comment]
Fixes #119

**Comment by Ninakoru** [comment]
> 
> 
> I'm pretty sure the UI label is hardcoded somewhere else.

Uhm.. not sure but the central number on the main window shows 3.0.0.0 now.

BTW @EtienneLamoureux any ETA for a new release? it seems you are quite busy on other things... Thanks for your work.

**Comment by EtienneLamoureux** [comment]
Ok thanks. 
I'll release the new version not this weekend but the other.

**Comment by EtienneLamoureux** [comment]
If @epinter or @northfury feel like sending me a zip of thr latest built code, I could release earlier.

**Pull request merged**
