### PR TITLE
Add character class and level to character selection dropdown

### LINKED ISSUE #125: Add character class and level to character selection dropdown
Hello.

Could you add more character related information to the list, when I choose my character inventory? I mean, it only shows my character names, but would be nice to see the character level and class name.

Thanks for your work. :)

### PR DESCRIPTION
**Pull request by hguy**
Fix #125

### CODE REVIEW

**Comment by hguy** [comment]
Details are displayed when the player info is loaded.
With "Preload All Files" setting enabled everything is set from the beginning.
image

**Comment by EtienneLamoureux** [comment]
Thanks for respecting the format specified in the issue!

**Comment by hguy** [comment]
> 
> 
> Thanks for respecting the format specified in the issue!

@EtienneLamoureux You mean `<Etienne>, <Lamoureux> - Level: <99>` ? I though `<xxx>` was a placeholder !

**Comment by EtienneLamoureux** [comment]
Included in https://github.com/EtienneLamoureux/TQVaultAE/pull/266

**Pull request closed without merging**
