### PR TITLE
Fix #282, Enable Hot Reload

### LINKED ISSUE #282: Enable reloading the tool's stashes while the game is running
Refresh TQVaultAE data when files are modified "in game".

- [x] Add a checkbox in settings for activation (Default : false, maybe one for each storage type)
- [ ] ~~Add notification when it happens~~

### PR DESCRIPTION
**Pull request by hguy**
**Activate Hot Reload**
image

**TQVault is Restarting**
From there TQVaultAE reload every file update in real time.

**Files Handling**
- Player Equipment & Inventory (for all loaded character in TQVaultAE)
- Player Storage Area (for all loaded character in TQVaultAE)
- Relic Vault
- Transfer Area

**Note**
All "in game" update of a monitored save file (Player, Stash, Transfer Stash, Relic Stash) are visible in real time in TQVaultAE.
In case you have unsaved changes in TQVaultAE, the "in game" saving system prevail and override your changes.
You still have to close TQVaultAE to apply your changes.

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
Interesting. How does it behave when the game is open and you make changes in the vault and then save? Can you lose game progress?

**Comment by EtienneLamoureux** [comment]
Could you also update the F.A.Q. blurb about this and mention the new option?
> Q. Can I use TQVaultAE while playing the game?

**Comment by hguy** [comment]
> Interesting. Is there any way to lose game progress at all?

I don't see how! That make TQVaultAE a slave to what's happening in game and chose to sacrifice unsaved changes made in TQVaultAE for it. 
As far as i know, even if you mess with the player.chr ou have open in game, it will be overwritten by the last "in game" state when you open the inventory in game.

**Comment by hguy** [comment]
> Could you also update the F.A.Q. blurb about this and mention the new option?
> 
> > Q. Can I use TQVaultAE while playing the game?

Done

**Pull request merged**
