### PR TITLE
Refacto split gui

### PR DESCRIPTION
**Pull request by epinter**

### CODE REVIEW

**Comment by epinter** [comment]
@hguy this is what I mean ... So we can merge without squash

**Comment by hguy** [comment]
I'm not git fluent any hint on how to achieve this ?
Looks like squashing old commit not that simple.

**Comment by epinter** [comment]
I can help you. Just sent an email.

**Comment by hguy** [comment]
Thank you !
Looks like the problem is i create my new branch from origin/master and not from upstream/master

**Pull request closed without merging**
