### PR TITLE
Code base rejuvenation

### PR DESCRIPTION
**Pull request by hguy**
- Base layers becomes NETSTANDARD for a wider environment compatibility. You can now think of using it in a Linux/Mono/AspNet runtime if you like (ExpressionEval, Data, Entities, Logs).
- Get ride of Tao.Devil C lib and use https://www.nuget.org/packages/DDSReader/ for a pure .NET DDStoBitmap conversion.
- Upgrade Target Framework to Net4.7.2 To be able to use netstandard2.0
- Better handling of VXPLibrary.dll & VXPLib.dll output. The time we find a pure .NET alternative
- "Release Build" does not have problem to run anymore. Probably something related to Tao.Devil C Lib.
- Split DAL Model/Provider

### CODE REVIEW

**Comment by NorthFury** [comment]
Wow... that's quite a bit of work in there. I'm mostly a JVM guy so I'll only be able to do a review on the non .NET specific changes.

**Comment by epinter** [comment]
Removing INI file support ?

**Comment by hguy** [comment]
> Great work on modernizing the application this way.
- Thanks that great tool needs love :)
> Removing INI file support ? Users often complain about edit a xml file.
- The ini file was handled by classes using `[DllImport("kernel32", CharSet = CharSet.Unicode)]` Windows OS specific and a big part of this refacto is to make all the underlying layers (except GUI) OS agnostic (netstandard2.0).
- And IMO having your configuration spread over multiple files and various format have no sense. Proper documentation on app.config edition related to specific needs greatly help user support.
> About the custom font, last time I tried without the gdi32 import, the font didn't work if not installed in the system (c:\windows\fonts). It's working now ?
- As far as i know font installation is required for developers (proper rendering in visual studio winform designer) but at runtime the fonts are hot loaded in memory from resource files.

**Comment by hguy** [comment]
> Wow... that's quite a bit of work in there. I'm mostly a JVM guy so I'll only be able to do a review on the non .NET specific changes.
- From non .NET specific point of view, code spliting strategy is  based on area of code responsibility and versatility for reusability from the bottom up (Data -> UI).
- Going forward should now taking the opposite direction (UI -> Data) to reduce responsibility of TQVaultAE.GUI to underlying layers possibly giving birth to a new "Services" layer in between.
- I'm still questioning myself about Resources locations, Pure .NET tooltip replacement, etc...

**Comment by NorthFury** [comment]
I meant I can't properly review project structure and dependencies changes. It does sound good though.

As far as code organization goes I did a fair share of refactoring myself, just not in this project.

**Comment by EtienneLamoureux** [comment]
So I can see the bulk of the changes come from splitting DAL 
I don't think there will be any significant issues getting this in.
Could you provide a quick sketch of the new interaction between the layers?

**Comment by hguy** [comment]
Yes it look like this with this change.
https://tinyurl.com/y63jaawp

**Comment by hguy** [comment]
But it may be better to not wait all these steps before merging. Just to provide that massive amount of changes to others who could contribute meantime.

**Comment by EtienneLamoureux** [comment]
Of course. I'll go over this one more time this weekend.

**Comment by epinter** [comment]
This work is finished ? The font loading is broken since the commit d5d12ab20967d3a3014954c78a55581ac30737e7 (see the comments in PR https://github.com/EtienneLamoureux/TQVaultAE/pull/105), but the custom font code was updated...

We are keeping the custom font code ?

**Comment by hguy** [comment]
I just 

> 
> 
> This work is finished ? The font loading is broken since the commit [d5d12ab](https://github.com/EtienneLamoureux/TQVaultAE/commit/d5d12ab20967d3a3014954c78a55581ac30737e7) (see the comments in PR #105), but the custom font code was updated...
> 
> We are keeping the custom font code ?

I just maked a PR fixing this.

**Pull request merged**
