### PR TITLE
Unlock Masteries at level 2 and level 8 on level increase and lock it on level downgrade

### PR DESCRIPTION
**Pull request by hguy**
**Warning :** Still need mastery choice reset and skill point release on level downgrade. But i'ts fine for level 1 character boost.

### CODE REVIEW

**Comment by hguy** [comment]
this Fix #249.

**Comment by EtienneLamoureux** [comment]
For the future enhancement: I would also like to block level-down from happening if there aren't enough unassigned points to remove.

**Comment by hguy** [comment]
And a simple "Masteries Reset" button would be nice. 
Sometimes i just want to "respec & try" again  and again without making alts.

**Comment by hguy** [comment]
Add "Masteries Reset" with invested skill point release.

image

**Comment by EtienneLamoureux** [comment]
Included in https://github.com/EtienneLamoureux/TQVaultAE/pull/266

**Pull request closed without merging**
