### PR TITLE
Unclutter TQVaultAE.GUI

### PR DESCRIPTION
**Pull request by hguy**
It was messy

### CODE REVIEW

**Comment by EtienneLamoureux** [comment]
Thanks for this, the project is quite historical and contribution guidelines have always been lacking!
Since this is significant, I'll wait until we figure out the mew expansion to take this PR in, as not to mess up everyone working on the current code.

**Comment by hguy** [comment]
Yes i agree ! Expansion first 👍

**Comment by EtienneLamoureux** [comment]
We could go ahead with this

**Comment by hguy** [comment]
Any problem with the review ?

**Comment by NorthFury** [comment]
There are conflicts in this PR. could you please solve them?

**Comment by hguy** [comment]
Should be OK

**Comment by EtienneLamoureux** [comment]
Thanks for fixing the conflicts, I'll review over the course of next week.

**Comment by hguy** [comment]
if you finaly consider merging #133 it should be done before this one (to avoid headache) :)

**Comment by hguy** [comment]
Merge is Ok

**Pull request merged**
