### PR TITLE
The Forge : New crafting system + Highlight items quick search

### PR DESCRIPTION
**Pull request by hguy**
## Improved Loading Performance
- Database.LoadResource() and Database.GetRecordFromFile() has been slightly rewritten and use cache.
- Removed cache on ArzFileProvider.GetItem()
- Noticeable with option "Preload all"

## Extended object model
- Item.HasPrefix
- Item.HasSuffix
- Item.AcceptExtraRelic
- Item.GearLevel
- Item.IsJewellery
- Item.GearType
- Item.IsRelicAllowed
- Item.TryGetAllowedGearTypes
- RelicAndCharm Enum
- GearType Enum
- GearLevel Enum

## Sound system
TQVaultAE have a basic sound service now that we (dev) can use and enhance.
It use the game resource audio files.

## The Forge : New crafting system
This new feature transform TQVaultAE into a crafting bench.
- Translation FR/EN.
- Documentation included (more details).

### Forge UI
image

### Notifications
image

### Example Relax Mode
image

### Example God Mode
image

## Highlight items quick search

This QoL improvement allows you to find something quickly into your clutered vaults.
- Translation FR/EN.
- Documentation included.

### Vault and Player
image
### With secondary vault
image

It also provide extended filters by clicking on the label.
image

### CODE REVIEW

**Comment by hguy** [comment]
Updated UI
image

**Comment by hguy** [comment]
This PR is a propososal for #144 and #284

**Comment by EtienneLamoureux** [comment]
This is quite the new feature, let me think about this.

**Comment by hguy** [comment]
> So the strict mode respects the item type (helmet-only affixes on helmets, etc.)

Yes but by restricting the item type you can slot into prefix/suffix (i don't look at some loottable in the game database).

> Relax can put any affix on items that can have affixes

Every Titan Quest items can have affixes. Is the game gonna use it ? That's another question.

> God mode is complete bonkers, anything goes, that item is clearly cheated

Yes you can create grotesque item

> And this whole thing is only available with the "edit objects" cheat on?

The Forge is an "Item Editing" feature yes.

Here's the like to the futur documentation
https://github.com/hguy/TQVaultAE/blob/highlight/FORGE.md#crafting-modes

**Comment by DinosaurGamer** [comment]
Can you tell me how I access The Forge in TQVaultAE?

By the way, thanks for keeping the Titan Quest experience alive...especially for us old timers.

**Comment by EtienneLamoureux** [comment]
@DinosaurGamer next release will have it :D

**Comment by DinosaurGamer** [comment]
Thanks so much, Etienne & HGUY!

Unfortunately, "compiling the project" is way beyond my abilities now...my programming days ended with the Apple II+.  :-)

Really looking forward to your new TQVault release with The Forge!

It's nostalgic games like Titan Quest, Diablo, Master of Magic, and Master of Orion that keep people like me connected to relatives/friends who have now moved across the globe.

Thanks again for keeping the Titan Quest fun going for us!!!

**Review by EtienneLamoureux — APPROVED** [review]

**Comment by DinosaurGamer** [comment]
I read through the docs for The Forge, and the features look great!

Again, thanks Etienne and HGUY for putting in so much of your time on this!

**Comment by hguy** [comment]
> I read through the docs for The Forge, and the features look great!
> 
> Again, thanks Etienne and HGUY for putting in so much of your time on this!

Thanks!
TQ have a crafting system now. It's time to enjoy it ;)

**Comment by EtienneLamoureux** [comment]
> Hi HGUY!
> 
> I would love to try out The Forge, it looks really cool!
> 
> But sadly, I have no idea how to run the code. :-(
> 
> ```
>       https://github.com/hguy/TQVaultAE/find/highlight
> ```

The forge is available in [release 4.1.0](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/4.1.0) via a new button at the top of the screen.

**Comment by DinosaurGamer** [comment]
Hi Etienne,

I'm sorry, I didn't realize TQVault 4.10 was released.

I definitely have to check the latest version out.

Much appreciated to HGUY and you!!!

**Comment by DinosaurGamer** [comment]
Hello HGUY and Etienne,

Thanks much for your work on The Forge.

It's been a lot of fun tinkering with it and playing around with new character buildouts/equipment.

Again, really appreciate the time you guys put into The Forge!

**Comment by DinosaurGamer** [comment]
Hi HGUY and Etienne,

I hope your summer's going great!

Been having a lot of fun with the Forge, but sadly, I think the latest TQ patch broke the Forge so it no longer works...  :-(

**Pull request merged**
